/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProductBacklogIndexLazyImport = createFileRoute('/product-backlog/')()
const ProductBacklogTaskEditorLazyImport = createFileRoute(
  '/product-backlog/task-editor',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductBacklogIndexLazyRoute = ProductBacklogIndexLazyImport.update({
  id: '/product-backlog/',
  path: '/product-backlog/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/product-backlog/index.lazy').then((d) => d.Route),
)

const ProductBacklogTaskEditorLazyRoute =
  ProductBacklogTaskEditorLazyImport.update({
    id: '/product-backlog/task-editor',
    path: '/product-backlog/task-editor',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/product-backlog/task-editor.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/product-backlog/task-editor': {
      id: '/product-backlog/task-editor'
      path: '/product-backlog/task-editor'
      fullPath: '/product-backlog/task-editor'
      preLoaderRoute: typeof ProductBacklogTaskEditorLazyImport
      parentRoute: typeof rootRoute
    }
    '/product-backlog/': {
      id: '/product-backlog/'
      path: '/product-backlog'
      fullPath: '/product-backlog'
      preLoaderRoute: typeof ProductBacklogIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorLazyRoute
  '/product-backlog': typeof ProductBacklogIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorLazyRoute
  '/product-backlog': typeof ProductBacklogIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorLazyRoute
  '/product-backlog/': typeof ProductBacklogIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product-backlog/task-editor' | '/product-backlog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product-backlog/task-editor' | '/product-backlog'
  id: '__root__' | '/' | '/product-backlog/task-editor' | '/product-backlog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProductBacklogTaskEditorLazyRoute: typeof ProductBacklogTaskEditorLazyRoute
  ProductBacklogIndexLazyRoute: typeof ProductBacklogIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProductBacklogTaskEditorLazyRoute: ProductBacklogTaskEditorLazyRoute,
  ProductBacklogIndexLazyRoute: ProductBacklogIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product-backlog/task-editor",
        "/product-backlog/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/product-backlog/task-editor": {
      "filePath": "product-backlog/task-editor.lazy.tsx"
    },
    "/product-backlog/": {
      "filePath": "product-backlog/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
