/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductBacklogIndexImport } from './routes/product-backlog/index'
import { Route as ProductBacklogTaskEditorImport } from './routes/product-backlog/task-editor'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductBacklogIndexRoute = ProductBacklogIndexImport.update({
  id: '/product-backlog/',
  path: '/product-backlog/',
  getParentRoute: () => rootRoute,
} as any)

const ProductBacklogTaskEditorRoute = ProductBacklogTaskEditorImport.update({
  id: '/product-backlog/task-editor',
  path: '/product-backlog/task-editor',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/product-backlog/task-editor': {
      id: '/product-backlog/task-editor'
      path: '/product-backlog/task-editor'
      fullPath: '/product-backlog/task-editor'
      preLoaderRoute: typeof ProductBacklogTaskEditorImport
      parentRoute: typeof rootRoute
    }
    '/product-backlog/': {
      id: '/product-backlog/'
      path: '/product-backlog'
      fullPath: '/product-backlog'
      preLoaderRoute: typeof ProductBacklogIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorRoute
  '/product-backlog': typeof ProductBacklogIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorRoute
  '/product-backlog': typeof ProductBacklogIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/product-backlog/task-editor': typeof ProductBacklogTaskEditorRoute
  '/product-backlog/': typeof ProductBacklogIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product-backlog/task-editor' | '/product-backlog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product-backlog/task-editor' | '/product-backlog'
  id: '__root__' | '/' | '/product-backlog/task-editor' | '/product-backlog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductBacklogTaskEditorRoute: typeof ProductBacklogTaskEditorRoute
  ProductBacklogIndexRoute: typeof ProductBacklogIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductBacklogTaskEditorRoute: ProductBacklogTaskEditorRoute,
  ProductBacklogIndexRoute: ProductBacklogIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product-backlog/task-editor",
        "/product-backlog/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/product-backlog/task-editor": {
      "filePath": "product-backlog/task-editor.tsx"
    },
    "/product-backlog/": {
      "filePath": "product-backlog/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
